Repository team-fusionx/CarND-Capstone, pull requests merged in 2018-08, with the labels that each got.

#142 Add second level of magnification to detect traffic light status
  ros/src/tl_detector/light_classification/tl_classifier.py
  ros/src/tl_detector/tl_detector.py
Labels: TL Detection

#143 Increase speed at which car can transition to creeping to lights
  ros/src/waypoint_updater/waypnt_updater.py
Labels: Waypoint Updater

#144 DBW: Increase steering LPF tau to 0.4 to reduce initial steer correction
  ros/src/twist_controller/twist_controller_mod.py
Labels: DBW

#146 Waypoint Follower: Increase min lookahead distance for Carla test
  ros/src/waypoint_follower/include/pure_pursuit_core.h
Labels: Waypoint Follower

#148 Pass images into deque to achieve max images processed with min latency
  ros/src/tl_detector/tl_detector.py
Labels: TL Detection

#149 TL Detector: Add dummy image for CLASSIFY_BY_GROUND_TRUTH
  ros/src/tl_detector/tl_detector.py
Labels: TL Detection
